/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package Api;

import Invokers.ApiException;
import Model.PtsV2PaymentsRefundPost400Response;
import Model.UmsV1UsersGet200Response;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserManagementApi
 */
@Ignore
public class UserManagementApiTest {

    private final UserManagementApi api = new UserManagementApi();

    
    /**
     * Get User Information
     *
     * This endpoint is to get all the user information depending on the filter criteria passed in the query.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUsersTest() throws ApiException {
        String organizationId = null;
        String userName = null;
        String permissionId = null;
        String roleId = null;
        UmsV1UsersGet200Response response = api.getUsers(organizationId, userName, permissionId, roleId);

        // TODO: test validations
    }
    
}
