/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package Model;

import java.util.Objects;
import java.util.Arrays;
import Model.CardProcessingConfigCommonAcquirerAgreementAcquirerCodePaymentOptions;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Contains the specific configuration details for an acquirer.
 */
@ApiModel(description = "Contains the specific configuration details for an acquirer.")

public class CardProcessingConfigCommonAcquirerAgreementAcquirerCode {
  @SerializedName("acquirerAccountId")
  private String acquirerAccountId = null;

  @SerializedName("summerBonusStartDate")
  private String summerBonusStartDate = null;

  @SerializedName("summerBonusEndDate")
  private String summerBonusEndDate = null;

  @SerializedName("summerBonusMonth")
  private String summerBonusMonth = null;

  @SerializedName("winterBonusStartDate")
  private String winterBonusStartDate = null;

  @SerializedName("winterBonusEndDate")
  private String winterBonusEndDate = null;

  @SerializedName("winterBonusMonth")
  private String winterBonusMonth = null;

  @SerializedName("numberOfInstallments")
  private String numberOfInstallments = null;

  @SerializedName("paymentModes")
  private String paymentModes = null;

  @SerializedName("numberOfInstallmentPayments")
  private String numberOfInstallmentPayments = null;

  @SerializedName("numberOfIntegratedInstallments")
  private String numberOfIntegratedInstallments = null;

  @SerializedName("numberOfBonusPayments")
  private String numberOfBonusPayments = null;

  @SerializedName("centerName")
  private String centerName = null;

  @SerializedName("fbnIdentificationFlag")
  private String fbnIdentificationFlag = null;

  @SerializedName("retailSupported")
  private Boolean retailSupported = null;

  @SerializedName("paymentOptions")
  private CardProcessingConfigCommonAcquirerAgreementAcquirerCodePaymentOptions paymentOptions = null;

  public CardProcessingConfigCommonAcquirerAgreementAcquirerCode acquirerAccountId(String acquirerAccountId) {
    this.acquirerAccountId = acquirerAccountId;
    return this;
  }

   /**
   * Account number for the acquirer.
   * @return acquirerAccountId
  **/
  @ApiModelProperty(value = "Account number for the acquirer.")
  public String getAcquirerAccountId() {
    return acquirerAccountId;
  }

  public void setAcquirerAccountId(String acquirerAccountId) {
    this.acquirerAccountId = acquirerAccountId;
  }

  public CardProcessingConfigCommonAcquirerAgreementAcquirerCode summerBonusStartDate(String summerBonusStartDate) {
    this.summerBonusStartDate = summerBonusStartDate;
    return this;
  }

   /**
   * Bonus start date for the summer period.
   * @return summerBonusStartDate
  **/
  @ApiModelProperty(value = "Bonus start date for the summer period.")
  public String getSummerBonusStartDate() {
    return summerBonusStartDate;
  }

  public void setSummerBonusStartDate(String summerBonusStartDate) {
    this.summerBonusStartDate = summerBonusStartDate;
  }

  public CardProcessingConfigCommonAcquirerAgreementAcquirerCode summerBonusEndDate(String summerBonusEndDate) {
    this.summerBonusEndDate = summerBonusEndDate;
    return this;
  }

   /**
   * Bonus end date for the summer period.
   * @return summerBonusEndDate
  **/
  @ApiModelProperty(value = "Bonus end date for the summer period.")
  public String getSummerBonusEndDate() {
    return summerBonusEndDate;
  }

  public void setSummerBonusEndDate(String summerBonusEndDate) {
    this.summerBonusEndDate = summerBonusEndDate;
  }

  public CardProcessingConfigCommonAcquirerAgreementAcquirerCode summerBonusMonth(String summerBonusMonth) {
    this.summerBonusMonth = summerBonusMonth;
    return this;
  }

   /**
   * Bonus month for the summer period .
   * @return summerBonusMonth
  **/
  @ApiModelProperty(value = "Bonus month for the summer period .")
  public String getSummerBonusMonth() {
    return summerBonusMonth;
  }

  public void setSummerBonusMonth(String summerBonusMonth) {
    this.summerBonusMonth = summerBonusMonth;
  }

  public CardProcessingConfigCommonAcquirerAgreementAcquirerCode winterBonusStartDate(String winterBonusStartDate) {
    this.winterBonusStartDate = winterBonusStartDate;
    return this;
  }

   /**
   * Bonus start date for the winter period.
   * @return winterBonusStartDate
  **/
  @ApiModelProperty(value = "Bonus start date for the winter period.")
  public String getWinterBonusStartDate() {
    return winterBonusStartDate;
  }

  public void setWinterBonusStartDate(String winterBonusStartDate) {
    this.winterBonusStartDate = winterBonusStartDate;
  }

  public CardProcessingConfigCommonAcquirerAgreementAcquirerCode winterBonusEndDate(String winterBonusEndDate) {
    this.winterBonusEndDate = winterBonusEndDate;
    return this;
  }

   /**
   * Bonus end date for the winter period.
   * @return winterBonusEndDate
  **/
  @ApiModelProperty(value = "Bonus end date for the winter period.")
  public String getWinterBonusEndDate() {
    return winterBonusEndDate;
  }

  public void setWinterBonusEndDate(String winterBonusEndDate) {
    this.winterBonusEndDate = winterBonusEndDate;
  }

  public CardProcessingConfigCommonAcquirerAgreementAcquirerCode winterBonusMonth(String winterBonusMonth) {
    this.winterBonusMonth = winterBonusMonth;
    return this;
  }

   /**
   * Bonus month for the winter period .
   * @return winterBonusMonth
  **/
  @ApiModelProperty(value = "Bonus month for the winter period .")
  public String getWinterBonusMonth() {
    return winterBonusMonth;
  }

  public void setWinterBonusMonth(String winterBonusMonth) {
    this.winterBonusMonth = winterBonusMonth;
  }

  public CardProcessingConfigCommonAcquirerAgreementAcquirerCode numberOfInstallments(String numberOfInstallments) {
    this.numberOfInstallments = numberOfInstallments;
    return this;
  }

   /**
   * Comma-separated list of the number of installments.
   * @return numberOfInstallments
  **/
  @ApiModelProperty(value = "Comma-separated list of the number of installments.")
  public String getNumberOfInstallments() {
    return numberOfInstallments;
  }

  public void setNumberOfInstallments(String numberOfInstallments) {
    this.numberOfInstallments = numberOfInstallments;
  }

  public CardProcessingConfigCommonAcquirerAgreementAcquirerCode paymentModes(String paymentModes) {
    this.paymentModes = paymentModes;
    return this;
  }

   /**
   * Comma-separated list of payment modes.
   * @return paymentModes
  **/
  @ApiModelProperty(value = "Comma-separated list of payment modes.")
  public String getPaymentModes() {
    return paymentModes;
  }

  public void setPaymentModes(String paymentModes) {
    this.paymentModes = paymentModes;
  }

  public CardProcessingConfigCommonAcquirerAgreementAcquirerCode numberOfInstallmentPayments(String numberOfInstallmentPayments) {
    this.numberOfInstallmentPayments = numberOfInstallmentPayments;
    return this;
  }

   /**
   * Comma-separated list of the number of installment payments.
   * @return numberOfInstallmentPayments
  **/
  @ApiModelProperty(value = "Comma-separated list of the number of installment payments.")
  public String getNumberOfInstallmentPayments() {
    return numberOfInstallmentPayments;
  }

  public void setNumberOfInstallmentPayments(String numberOfInstallmentPayments) {
    this.numberOfInstallmentPayments = numberOfInstallmentPayments;
  }

  public CardProcessingConfigCommonAcquirerAgreementAcquirerCode numberOfIntegratedInstallments(String numberOfIntegratedInstallments) {
    this.numberOfIntegratedInstallments = numberOfIntegratedInstallments;
    return this;
  }

   /**
   * Comma-separated list of the number of integrated installments.
   * @return numberOfIntegratedInstallments
  **/
  @ApiModelProperty(value = "Comma-separated list of the number of integrated installments.")
  public String getNumberOfIntegratedInstallments() {
    return numberOfIntegratedInstallments;
  }

  public void setNumberOfIntegratedInstallments(String numberOfIntegratedInstallments) {
    this.numberOfIntegratedInstallments = numberOfIntegratedInstallments;
  }

  public CardProcessingConfigCommonAcquirerAgreementAcquirerCode numberOfBonusPayments(String numberOfBonusPayments) {
    this.numberOfBonusPayments = numberOfBonusPayments;
    return this;
  }

   /**
   * Comma-separated list of the number of bonus payments.
   * @return numberOfBonusPayments
  **/
  @ApiModelProperty(value = "Comma-separated list of the number of bonus payments.")
  public String getNumberOfBonusPayments() {
    return numberOfBonusPayments;
  }

  public void setNumberOfBonusPayments(String numberOfBonusPayments) {
    this.numberOfBonusPayments = numberOfBonusPayments;
  }

  public CardProcessingConfigCommonAcquirerAgreementAcquirerCode centerName(String centerName) {
    this.centerName = centerName;
    return this;
  }

   /**
   * Center name provided by the acquirer.
   * @return centerName
  **/
  @ApiModelProperty(value = "Center name provided by the acquirer.")
  public String getCenterName() {
    return centerName;
  }

  public void setCenterName(String centerName) {
    this.centerName = centerName;
  }

  public CardProcessingConfigCommonAcquirerAgreementAcquirerCode fbnIdentificationFlag(String fbnIdentificationFlag) {
    this.fbnIdentificationFlag = fbnIdentificationFlag;
    return this;
  }

   /**
   * FBN (For Benefit Of) Identification flag.
   * @return fbnIdentificationFlag
  **/
  @ApiModelProperty(value = "FBN (For Benefit Of) Identification flag.")
  public String getFbnIdentificationFlag() {
    return fbnIdentificationFlag;
  }

  public void setFbnIdentificationFlag(String fbnIdentificationFlag) {
    this.fbnIdentificationFlag = fbnIdentificationFlag;
  }

  public CardProcessingConfigCommonAcquirerAgreementAcquirerCode retailSupported(Boolean retailSupported) {
    this.retailSupported = retailSupported;
    return this;
  }

   /**
   * Indicates if retail transactions are supported.
   * @return retailSupported
  **/
  @ApiModelProperty(value = "Indicates if retail transactions are supported.")
  public Boolean RetailSupported() {
    return retailSupported;
  }

  public void setRetailSupported(Boolean retailSupported) {
    this.retailSupported = retailSupported;
  }

  public CardProcessingConfigCommonAcquirerAgreementAcquirerCode paymentOptions(CardProcessingConfigCommonAcquirerAgreementAcquirerCodePaymentOptions paymentOptions) {
    this.paymentOptions = paymentOptions;
    return this;
  }

   /**
   * Get paymentOptions
   * @return paymentOptions
  **/
  @ApiModelProperty(value = "")
  public CardProcessingConfigCommonAcquirerAgreementAcquirerCodePaymentOptions getPaymentOptions() {
    return paymentOptions;
  }

  public void setPaymentOptions(CardProcessingConfigCommonAcquirerAgreementAcquirerCodePaymentOptions paymentOptions) {
    this.paymentOptions = paymentOptions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardProcessingConfigCommonAcquirerAgreementAcquirerCode cardProcessingConfigCommonAcquirerAgreementAcquirerCode = (CardProcessingConfigCommonAcquirerAgreementAcquirerCode) o;
    return Objects.equals(this.acquirerAccountId, cardProcessingConfigCommonAcquirerAgreementAcquirerCode.acquirerAccountId) &&
        Objects.equals(this.summerBonusStartDate, cardProcessingConfigCommonAcquirerAgreementAcquirerCode.summerBonusStartDate) &&
        Objects.equals(this.summerBonusEndDate, cardProcessingConfigCommonAcquirerAgreementAcquirerCode.summerBonusEndDate) &&
        Objects.equals(this.summerBonusMonth, cardProcessingConfigCommonAcquirerAgreementAcquirerCode.summerBonusMonth) &&
        Objects.equals(this.winterBonusStartDate, cardProcessingConfigCommonAcquirerAgreementAcquirerCode.winterBonusStartDate) &&
        Objects.equals(this.winterBonusEndDate, cardProcessingConfigCommonAcquirerAgreementAcquirerCode.winterBonusEndDate) &&
        Objects.equals(this.winterBonusMonth, cardProcessingConfigCommonAcquirerAgreementAcquirerCode.winterBonusMonth) &&
        Objects.equals(this.numberOfInstallments, cardProcessingConfigCommonAcquirerAgreementAcquirerCode.numberOfInstallments) &&
        Objects.equals(this.paymentModes, cardProcessingConfigCommonAcquirerAgreementAcquirerCode.paymentModes) &&
        Objects.equals(this.numberOfInstallmentPayments, cardProcessingConfigCommonAcquirerAgreementAcquirerCode.numberOfInstallmentPayments) &&
        Objects.equals(this.numberOfIntegratedInstallments, cardProcessingConfigCommonAcquirerAgreementAcquirerCode.numberOfIntegratedInstallments) &&
        Objects.equals(this.numberOfBonusPayments, cardProcessingConfigCommonAcquirerAgreementAcquirerCode.numberOfBonusPayments) &&
        Objects.equals(this.centerName, cardProcessingConfigCommonAcquirerAgreementAcquirerCode.centerName) &&
        Objects.equals(this.fbnIdentificationFlag, cardProcessingConfigCommonAcquirerAgreementAcquirerCode.fbnIdentificationFlag) &&
        Objects.equals(this.retailSupported, cardProcessingConfigCommonAcquirerAgreementAcquirerCode.retailSupported) &&
        Objects.equals(this.paymentOptions, cardProcessingConfigCommonAcquirerAgreementAcquirerCode.paymentOptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acquirerAccountId, summerBonusStartDate, summerBonusEndDate, summerBonusMonth, winterBonusStartDate, winterBonusEndDate, winterBonusMonth, numberOfInstallments, paymentModes, numberOfInstallmentPayments, numberOfIntegratedInstallments, numberOfBonusPayments, centerName, fbnIdentificationFlag, retailSupported, paymentOptions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardProcessingConfigCommonAcquirerAgreementAcquirerCode {\n");
    
    if (acquirerAccountId != null) sb.append("    acquirerAccountId: ").append(toIndentedString(acquirerAccountId)).append("\n");
    if (summerBonusStartDate != null) sb.append("    summerBonusStartDate: ").append(toIndentedString(summerBonusStartDate)).append("\n");
    if (summerBonusEndDate != null) sb.append("    summerBonusEndDate: ").append(toIndentedString(summerBonusEndDate)).append("\n");
    if (summerBonusMonth != null) sb.append("    summerBonusMonth: ").append(toIndentedString(summerBonusMonth)).append("\n");
    if (winterBonusStartDate != null) sb.append("    winterBonusStartDate: ").append(toIndentedString(winterBonusStartDate)).append("\n");
    if (winterBonusEndDate != null) sb.append("    winterBonusEndDate: ").append(toIndentedString(winterBonusEndDate)).append("\n");
    if (winterBonusMonth != null) sb.append("    winterBonusMonth: ").append(toIndentedString(winterBonusMonth)).append("\n");
    if (numberOfInstallments != null) sb.append("    numberOfInstallments: ").append(toIndentedString(numberOfInstallments)).append("\n");
    if (paymentModes != null) sb.append("    paymentModes: ").append(toIndentedString(paymentModes)).append("\n");
    if (numberOfInstallmentPayments != null) sb.append("    numberOfInstallmentPayments: ").append(toIndentedString(numberOfInstallmentPayments)).append("\n");
    if (numberOfIntegratedInstallments != null) sb.append("    numberOfIntegratedInstallments: ").append(toIndentedString(numberOfIntegratedInstallments)).append("\n");
    if (numberOfBonusPayments != null) sb.append("    numberOfBonusPayments: ").append(toIndentedString(numberOfBonusPayments)).append("\n");
    if (centerName != null) sb.append("    centerName: ").append(toIndentedString(centerName)).append("\n");
    if (fbnIdentificationFlag != null) sb.append("    fbnIdentificationFlag: ").append(toIndentedString(fbnIdentificationFlag)).append("\n");
    if (retailSupported != null) sb.append("    retailSupported: ").append(toIndentedString(retailSupported)).append("\n");
    if (paymentOptions != null) sb.append("    paymentOptions: ").append(toIndentedString(paymentOptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      // return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

