/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package Model;

import java.util.Objects;
import java.util.Arrays;
import Model.GetAllPlansResponseOrderInformationAmountDetails;
import Model.GetAllSubscriptionsResponseOrderInformationBillTo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GetAllSubscriptionsResponseOrderInformation
 */

public class GetAllSubscriptionsResponseOrderInformation {
  @SerializedName("amountDetails")
  private GetAllPlansResponseOrderInformationAmountDetails amountDetails = null;

  @SerializedName("billTo")
  private GetAllSubscriptionsResponseOrderInformationBillTo billTo = null;

  public GetAllSubscriptionsResponseOrderInformation amountDetails(GetAllPlansResponseOrderInformationAmountDetails amountDetails) {
    this.amountDetails = amountDetails;
    return this;
  }

   /**
   * Get amountDetails
   * @return amountDetails
  **/
  @ApiModelProperty(value = "")
  public GetAllPlansResponseOrderInformationAmountDetails getAmountDetails() {
    return amountDetails;
  }

  public void setAmountDetails(GetAllPlansResponseOrderInformationAmountDetails amountDetails) {
    this.amountDetails = amountDetails;
  }

  public GetAllSubscriptionsResponseOrderInformation billTo(GetAllSubscriptionsResponseOrderInformationBillTo billTo) {
    this.billTo = billTo;
    return this;
  }

   /**
   * Get billTo
   * @return billTo
  **/
  @ApiModelProperty(value = "")
  public GetAllSubscriptionsResponseOrderInformationBillTo getBillTo() {
    return billTo;
  }

  public void setBillTo(GetAllSubscriptionsResponseOrderInformationBillTo billTo) {
    this.billTo = billTo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAllSubscriptionsResponseOrderInformation getAllSubscriptionsResponseOrderInformation = (GetAllSubscriptionsResponseOrderInformation) o;
    return Objects.equals(this.amountDetails, getAllSubscriptionsResponseOrderInformation.amountDetails) &&
        Objects.equals(this.billTo, getAllSubscriptionsResponseOrderInformation.billTo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amountDetails, billTo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAllSubscriptionsResponseOrderInformation {\n");
    
    sb.append("    amountDetails: ").append(toIndentedString(amountDetails)).append("\n");
    sb.append("    billTo: ").append(toIndentedString(billTo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

