/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package Model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PtsV2PaymentsPost201ResponseEmbeddedActionsWATCHLISTSCREENING
 */

public class PtsV2PaymentsPost201ResponseEmbeddedActionsWATCHLISTSCREENING {
  @SerializedName("status")
  private String status = null;

  @SerializedName("reason")
  private String reason = null;

  @SerializedName("message")
  private String message = null;

  public PtsV2PaymentsPost201ResponseEmbeddedActionsWATCHLISTSCREENING status(String status) {
    this.status = status;
    return this;
  }

   /**
   * The status for the call can be: - COMPLETED - INVALID_REQUEST - DECLINED 
   * @return status
  **/
  @ApiModelProperty(value = "The status for the call can be: - COMPLETED - INVALID_REQUEST - DECLINED ")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public PtsV2PaymentsPost201ResponseEmbeddedActionsWATCHLISTSCREENING reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * The reason of the status. Value can be   - &#x60;CUSTOMER_WATCHLIST_MATCH&#x60;   - &#x60;ADDRESS_COUNTRY_WATCHLIST_MATCH&#x60;   - &#x60;EMAIL_COUNTRY_WATCHLIST_MATCH&#x60;   - &#x60;IP_COUNTRY_WATCHLIST_MATCH&#x60;   - &#x60;INVALID_MERCHANT_CONFIGURATION&#x60; 
   * @return reason
  **/
  @ApiModelProperty(value = "The reason of the status. Value can be   - `CUSTOMER_WATCHLIST_MATCH`   - `ADDRESS_COUNTRY_WATCHLIST_MATCH`   - `EMAIL_COUNTRY_WATCHLIST_MATCH`   - `IP_COUNTRY_WATCHLIST_MATCH`   - `INVALID_MERCHANT_CONFIGURATION` ")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public PtsV2PaymentsPost201ResponseEmbeddedActionsWATCHLISTSCREENING message(String message) {
    this.message = message;
    return this;
  }

   /**
   * The message describing the reason of the status. Value can be   - The customer matched the Denied Parties List   - The Export bill_country/ship_country  match   - Export email_country match   - Export hostname_country/ip_country match 
   * @return message
  **/
  @ApiModelProperty(value = "The message describing the reason of the status. Value can be   - The customer matched the Denied Parties List   - The Export bill_country/ship_country  match   - Export email_country match   - Export hostname_country/ip_country match ")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PtsV2PaymentsPost201ResponseEmbeddedActionsWATCHLISTSCREENING ptsV2PaymentsPost201ResponseEmbeddedActionsWATCHLISTSCREENING = (PtsV2PaymentsPost201ResponseEmbeddedActionsWATCHLISTSCREENING) o;
    return Objects.equals(this.status, ptsV2PaymentsPost201ResponseEmbeddedActionsWATCHLISTSCREENING.status) &&
        Objects.equals(this.reason, ptsV2PaymentsPost201ResponseEmbeddedActionsWATCHLISTSCREENING.reason) &&
        Objects.equals(this.message, ptsV2PaymentsPost201ResponseEmbeddedActionsWATCHLISTSCREENING.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, reason, message);
  }


  private static final java.util.regex.Pattern SENSITIVE_FIELD_PATTERN =
      java.util.regex.Pattern.compile(
          "^(password|apiKey|accessToken|refreshToken|clientSecret|secret|secretKey"
          + "|passphrase|privateKey|authToken|bearerToken|idToken"
          + "|sharedSecret|webhookSecret|keyPassword|encryptionKey|signingKey"
          + "|cardNumber|pan|cvv|cvn|cvv2|securityCode|pin|accountNumber"
          + "|number|expirationMonth|expirationYear|ssn|taxId)$");

  /**
   * Returns a masked string representation of this object.
   * Sensitive fields (passwords, API keys, card numbers, etc.) are replaced
   * with {@code [REDACTED]} to prevent accidental exposure in logs.
   *
   * <p>To inspect sensitive field values during local debugging, use
   * {@link #toDebugString()} instead, or call the individual getter methods.
   *
   * @return masked string representation
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PtsV2PaymentsPost201ResponseEmbeddedActionsWATCHLISTSCREENING {\n");
    
    if (status != null) sb.append("    status: ").append(SENSITIVE_FIELD_PATTERN.matcher("status").matches() ? "[REDACTED]" : toIndentedString(status)).append("\n");
    if (reason != null) sb.append("    reason: ").append(SENSITIVE_FIELD_PATTERN.matcher("reason").matches() ? "[REDACTED]" : toIndentedString(reason)).append("\n");
    if (message != null) sb.append("    message: ").append(SENSITIVE_FIELD_PATTERN.matcher("message").matches() ? "[REDACTED]" : toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Returns an unmasked string representation of this object, including all
   * sensitive field values in plaintext.
   *
   * <p><b>WARNING:</b> For local debugging only. Never pass this output to a
   * logger or include it in error messages in production environments, as it
   * will expose credentials, card numbers, and other sensitive data.
   *
   * @return unmasked string representation
   */
  public String toDebugString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PtsV2PaymentsPost201ResponseEmbeddedActionsWATCHLISTSCREENING {\n");
    
    if (status != null) sb.append("    status: ").append(toIndentedString(status)).append("\n");
    if (reason != null) sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    if (message != null) sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      // return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

