/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package Model;

import java.util.Objects;
import java.util.Arrays;
import Model.PtsV2PaymentsPost201ResponseTokenInformationCustomer;
import Model.PtsV2PaymentsPost201ResponseTokenInformationPaymentInstrument;
import Model.PtsV2PaymentsPost201ResponseTokenInformationShippingAddress;
import Model.TssV2TransactionsGet200ResponsePaymentInformationInstrumentIdentifier;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TssV2TransactionsGet200ResponseTokenInformation
 */

public class TssV2TransactionsGet200ResponseTokenInformation {
  @SerializedName("customer")
  private PtsV2PaymentsPost201ResponseTokenInformationCustomer customer = null;

  @SerializedName("paymentInstrument")
  private PtsV2PaymentsPost201ResponseTokenInformationPaymentInstrument paymentInstrument = null;

  @SerializedName("shippingAddress")
  private PtsV2PaymentsPost201ResponseTokenInformationShippingAddress shippingAddress = null;

  @SerializedName("instrumentIdentifier")
  private TssV2TransactionsGet200ResponsePaymentInformationInstrumentIdentifier instrumentIdentifier = null;

  @SerializedName("jti")
  private String jti = null;

  @SerializedName("transientTokenJwt")
  private String transientTokenJwt = null;

  public TssV2TransactionsGet200ResponseTokenInformation customer(PtsV2PaymentsPost201ResponseTokenInformationCustomer customer) {
    this.customer = customer;
    return this;
  }

   /**
   * Get customer
   * @return customer
  **/
  @ApiModelProperty(value = "")
  public PtsV2PaymentsPost201ResponseTokenInformationCustomer getCustomer() {
    return customer;
  }

  public void setCustomer(PtsV2PaymentsPost201ResponseTokenInformationCustomer customer) {
    this.customer = customer;
  }

  public TssV2TransactionsGet200ResponseTokenInformation paymentInstrument(PtsV2PaymentsPost201ResponseTokenInformationPaymentInstrument paymentInstrument) {
    this.paymentInstrument = paymentInstrument;
    return this;
  }

   /**
   * Get paymentInstrument
   * @return paymentInstrument
  **/
  @ApiModelProperty(value = "")
  public PtsV2PaymentsPost201ResponseTokenInformationPaymentInstrument getPaymentInstrument() {
    return paymentInstrument;
  }

  public void setPaymentInstrument(PtsV2PaymentsPost201ResponseTokenInformationPaymentInstrument paymentInstrument) {
    this.paymentInstrument = paymentInstrument;
  }

  public TssV2TransactionsGet200ResponseTokenInformation shippingAddress(PtsV2PaymentsPost201ResponseTokenInformationShippingAddress shippingAddress) {
    this.shippingAddress = shippingAddress;
    return this;
  }

   /**
   * Get shippingAddress
   * @return shippingAddress
  **/
  @ApiModelProperty(value = "")
  public PtsV2PaymentsPost201ResponseTokenInformationShippingAddress getShippingAddress() {
    return shippingAddress;
  }

  public void setShippingAddress(PtsV2PaymentsPost201ResponseTokenInformationShippingAddress shippingAddress) {
    this.shippingAddress = shippingAddress;
  }

  public TssV2TransactionsGet200ResponseTokenInformation instrumentIdentifier(TssV2TransactionsGet200ResponsePaymentInformationInstrumentIdentifier instrumentIdentifier) {
    this.instrumentIdentifier = instrumentIdentifier;
    return this;
  }

   /**
   * Get instrumentIdentifier
   * @return instrumentIdentifier
  **/
  @ApiModelProperty(value = "")
  public TssV2TransactionsGet200ResponsePaymentInformationInstrumentIdentifier getInstrumentIdentifier() {
    return instrumentIdentifier;
  }

  public void setInstrumentIdentifier(TssV2TransactionsGet200ResponsePaymentInformationInstrumentIdentifier instrumentIdentifier) {
    this.instrumentIdentifier = instrumentIdentifier;
  }

  public TssV2TransactionsGet200ResponseTokenInformation jti(String jti) {
    this.jti = jti;
    return this;
  }

   /**
   * TMS Transient Token, 64 hexadecimal id value representing captured payment credentials (including Sensitive Authentication Data, e.g. CVV). 
   * @return jti
  **/
  @ApiModelProperty(value = "TMS Transient Token, 64 hexadecimal id value representing captured payment credentials (including Sensitive Authentication Data, e.g. CVV). ")
  public String getJti() {
    return jti;
  }

  public void setJti(String jti) {
    this.jti = jti;
  }

  public TssV2TransactionsGet200ResponseTokenInformation transientTokenJwt(String transientTokenJwt) {
    this.transientTokenJwt = transientTokenJwt;
    return this;
  }

   /**
   * Flex API Transient Token encoded as JWT (JSON Web Token), e.g. Flex microform or Unified Payment checkout result. 
   * @return transientTokenJwt
  **/
  @ApiModelProperty(value = "Flex API Transient Token encoded as JWT (JSON Web Token), e.g. Flex microform or Unified Payment checkout result. ")
  public String getTransientTokenJwt() {
    return transientTokenJwt;
  }

  public void setTransientTokenJwt(String transientTokenJwt) {
    this.transientTokenJwt = transientTokenJwt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TssV2TransactionsGet200ResponseTokenInformation tssV2TransactionsGet200ResponseTokenInformation = (TssV2TransactionsGet200ResponseTokenInformation) o;
    return Objects.equals(this.customer, tssV2TransactionsGet200ResponseTokenInformation.customer) &&
        Objects.equals(this.paymentInstrument, tssV2TransactionsGet200ResponseTokenInformation.paymentInstrument) &&
        Objects.equals(this.shippingAddress, tssV2TransactionsGet200ResponseTokenInformation.shippingAddress) &&
        Objects.equals(this.instrumentIdentifier, tssV2TransactionsGet200ResponseTokenInformation.instrumentIdentifier) &&
        Objects.equals(this.jti, tssV2TransactionsGet200ResponseTokenInformation.jti) &&
        Objects.equals(this.transientTokenJwt, tssV2TransactionsGet200ResponseTokenInformation.transientTokenJwt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customer, paymentInstrument, shippingAddress, instrumentIdentifier, jti, transientTokenJwt);
  }


  private static final java.util.regex.Pattern SENSITIVE_FIELD_PATTERN =
      java.util.regex.Pattern.compile(
          "^(password|apiKey|accessToken|refreshToken|clientSecret|secret|secretKey"
          + "|passphrase|privateKey|authToken|bearerToken|idToken"
          + "|sharedSecret|webhookSecret|keyPassword|encryptionKey|signingKey"
          + "|cardNumber|pan|cvv|cvn|cvv2|securityCode|pin|accountNumber"
          + "|number|expirationMonth|expirationYear|ssn|taxId)$");

  /**
   * Returns a masked string representation of this object.
   * Sensitive fields (passwords, API keys, card numbers, etc.) are replaced
   * with {@code [REDACTED]} to prevent accidental exposure in logs.
   *
   * <p>To inspect sensitive field values during local debugging, use
   * {@link #toDebugString()} instead, or call the individual getter methods.
   *
   * @return masked string representation
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TssV2TransactionsGet200ResponseTokenInformation {\n");
    
    if (customer != null) sb.append("    customer: ").append(SENSITIVE_FIELD_PATTERN.matcher("customer").matches() ? "[REDACTED]" : toIndentedString(customer)).append("\n");
    if (paymentInstrument != null) sb.append("    paymentInstrument: ").append(SENSITIVE_FIELD_PATTERN.matcher("paymentInstrument").matches() ? "[REDACTED]" : toIndentedString(paymentInstrument)).append("\n");
    if (shippingAddress != null) sb.append("    shippingAddress: ").append(SENSITIVE_FIELD_PATTERN.matcher("shippingAddress").matches() ? "[REDACTED]" : toIndentedString(shippingAddress)).append("\n");
    if (instrumentIdentifier != null) sb.append("    instrumentIdentifier: ").append(SENSITIVE_FIELD_PATTERN.matcher("instrumentIdentifier").matches() ? "[REDACTED]" : toIndentedString(instrumentIdentifier)).append("\n");
    if (jti != null) sb.append("    jti: ").append(SENSITIVE_FIELD_PATTERN.matcher("jti").matches() ? "[REDACTED]" : toIndentedString(jti)).append("\n");
    if (transientTokenJwt != null) sb.append("    transientTokenJwt: ").append(SENSITIVE_FIELD_PATTERN.matcher("transientTokenJwt").matches() ? "[REDACTED]" : toIndentedString(transientTokenJwt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Returns an unmasked string representation of this object, including all
   * sensitive field values in plaintext.
   *
   * <p><b>WARNING:</b> For local debugging only. Never pass this output to a
   * logger or include it in error messages in production environments, as it
   * will expose credentials, card numbers, and other sensitive data.
   *
   * @return unmasked string representation
   */
  public String toDebugString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TssV2TransactionsGet200ResponseTokenInformation {\n");
    
    if (customer != null) sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    if (paymentInstrument != null) sb.append("    paymentInstrument: ").append(toIndentedString(paymentInstrument)).append("\n");
    if (shippingAddress != null) sb.append("    shippingAddress: ").append(toIndentedString(shippingAddress)).append("\n");
    if (instrumentIdentifier != null) sb.append("    instrumentIdentifier: ").append(toIndentedString(instrumentIdentifier)).append("\n");
    if (jti != null) sb.append("    jti: ").append(toIndentedString(jti)).append("\n");
    if (transientTokenJwt != null) sb.append("    transientTokenJwt: ").append(toIndentedString(transientTokenJwt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      // return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

