/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package Model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Aggregate monetary total of all debit (outgoing) entries within this ACH/BACS batch, used for batch-level balancing
 */
@ApiModel(description = "Aggregate monetary total of all debit (outgoing) entries within this ACH/BACS batch, used for batch-level balancing")

public class UnifiedriskTransactionBatchDetailsBatchDebitsAmount {
  @SerializedName("baseCurrency")
  private String baseCurrency = null;

  @SerializedName("baseValue")
  private String baseValue = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("value")
  private String value = null;

  @SerializedName("merchantCurrency")
  private String merchantCurrency = null;

  @SerializedName("merchantValue")
  private String merchantValue = null;

  public UnifiedriskTransactionBatchDetailsBatchDebitsAmount baseCurrency(String baseCurrency) {
    this.baseCurrency = baseCurrency;
    return this;
  }

   /**
   * ISO 4217 3-letter base reference currency for batch debit amounts
   * @return baseCurrency
  **/
  @ApiModelProperty(value = "ISO 4217 3-letter base reference currency for batch debit amounts")
  public String getBaseCurrency() {
    return baseCurrency;
  }

  public void setBaseCurrency(String baseCurrency) {
    this.baseCurrency = baseCurrency;
  }

  public UnifiedriskTransactionBatchDetailsBatchDebitsAmount baseValue(String baseValue) {
    this.baseValue = baseValue;
    return this;
  }

   /**
   * Total value of batch debit entries in the base reference currency
   * @return baseValue
  **/
  @ApiModelProperty(value = "Total value of batch debit entries in the base reference currency")
  public String getBaseValue() {
    return baseValue;
  }

  public void setBaseValue(String baseValue) {
    this.baseValue = baseValue;
  }

  public UnifiedriskTransactionBatchDetailsBatchDebitsAmount currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * ISO 4217 3-letter transaction currency for batch debit totals
   * @return currency
  **/
  @ApiModelProperty(value = "ISO 4217 3-letter transaction currency for batch debit totals")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public UnifiedriskTransactionBatchDetailsBatchDebitsAmount value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Total monetary value of all debit entries in this batch in the transaction currency
   * @return value
  **/
  @ApiModelProperty(value = "Total monetary value of all debit entries in this batch in the transaction currency")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public UnifiedriskTransactionBatchDetailsBatchDebitsAmount merchantCurrency(String merchantCurrency) {
    this.merchantCurrency = merchantCurrency;
    return this;
  }

   /**
   * ISO 4217 3-letter code for the merchant&#39;s local currency used to express the batch debits total
   * @return merchantCurrency
  **/
  @ApiModelProperty(value = "ISO 4217 3-letter code for the merchant's local currency used to express the batch debits total")
  public String getMerchantCurrency() {
    return merchantCurrency;
  }

  public void setMerchantCurrency(String merchantCurrency) {
    this.merchantCurrency = merchantCurrency;
  }

  public UnifiedriskTransactionBatchDetailsBatchDebitsAmount merchantValue(String merchantValue) {
    this.merchantValue = merchantValue;
    return this;
  }

   /**
   * Total batch debit amount expressed in the merchant&#39;s local currency for reconciliation
   * @return merchantValue
  **/
  @ApiModelProperty(value = "Total batch debit amount expressed in the merchant's local currency for reconciliation")
  public String getMerchantValue() {
    return merchantValue;
  }

  public void setMerchantValue(String merchantValue) {
    this.merchantValue = merchantValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnifiedriskTransactionBatchDetailsBatchDebitsAmount unifiedriskTransactionBatchDetailsBatchDebitsAmount = (UnifiedriskTransactionBatchDetailsBatchDebitsAmount) o;
    return Objects.equals(this.baseCurrency, unifiedriskTransactionBatchDetailsBatchDebitsAmount.baseCurrency) &&
        Objects.equals(this.baseValue, unifiedriskTransactionBatchDetailsBatchDebitsAmount.baseValue) &&
        Objects.equals(this.currency, unifiedriskTransactionBatchDetailsBatchDebitsAmount.currency) &&
        Objects.equals(this.value, unifiedriskTransactionBatchDetailsBatchDebitsAmount.value) &&
        Objects.equals(this.merchantCurrency, unifiedriskTransactionBatchDetailsBatchDebitsAmount.merchantCurrency) &&
        Objects.equals(this.merchantValue, unifiedriskTransactionBatchDetailsBatchDebitsAmount.merchantValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(baseCurrency, baseValue, currency, value, merchantCurrency, merchantValue);
  }


  private static final java.util.regex.Pattern SENSITIVE_FIELD_PATTERN =
      java.util.regex.Pattern.compile(
          "^(password|apiKey|accessToken|refreshToken|clientSecret|secret|secretKey"
          + "|passphrase|privateKey|authToken|bearerToken|idToken"
          + "|sharedSecret|webhookSecret|keyPassword|encryptionKey|signingKey"
          + "|cardNumber|pan|cvv|cvn|cvv2|securityCode|pin|accountNumber"
          + "|number|expirationMonth|expirationYear|ssn|taxId)$");

  /**
   * Returns a masked string representation of this object.
   * Sensitive fields (passwords, API keys, card numbers, etc.) are replaced
   * with {@code [REDACTED]} to prevent accidental exposure in logs.
   *
   * <p>To inspect sensitive field values during local debugging, use
   * {@link #toDebugString()} instead, or call the individual getter methods.
   *
   * @return masked string representation
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnifiedriskTransactionBatchDetailsBatchDebitsAmount {\n");
    
    if (baseCurrency != null) sb.append("    baseCurrency: ").append(SENSITIVE_FIELD_PATTERN.matcher("baseCurrency").matches() ? "[REDACTED]" : toIndentedString(baseCurrency)).append("\n");
    if (baseValue != null) sb.append("    baseValue: ").append(SENSITIVE_FIELD_PATTERN.matcher("baseValue").matches() ? "[REDACTED]" : toIndentedString(baseValue)).append("\n");
    if (currency != null) sb.append("    currency: ").append(SENSITIVE_FIELD_PATTERN.matcher("currency").matches() ? "[REDACTED]" : toIndentedString(currency)).append("\n");
    if (value != null) sb.append("    value: ").append(SENSITIVE_FIELD_PATTERN.matcher("value").matches() ? "[REDACTED]" : toIndentedString(value)).append("\n");
    if (merchantCurrency != null) sb.append("    merchantCurrency: ").append(SENSITIVE_FIELD_PATTERN.matcher("merchantCurrency").matches() ? "[REDACTED]" : toIndentedString(merchantCurrency)).append("\n");
    if (merchantValue != null) sb.append("    merchantValue: ").append(SENSITIVE_FIELD_PATTERN.matcher("merchantValue").matches() ? "[REDACTED]" : toIndentedString(merchantValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Returns an unmasked string representation of this object, including all
   * sensitive field values in plaintext.
   *
   * <p><b>WARNING:</b> For local debugging only. Never pass this output to a
   * logger or include it in error messages in production environments, as it
   * will expose credentials, card numbers, and other sensitive data.
   *
   * @return unmasked string representation
   */
  public String toDebugString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnifiedriskTransactionBatchDetailsBatchDebitsAmount {\n");
    
    if (baseCurrency != null) sb.append("    baseCurrency: ").append(toIndentedString(baseCurrency)).append("\n");
    if (baseValue != null) sb.append("    baseValue: ").append(toIndentedString(baseValue)).append("\n");
    if (currency != null) sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    if (value != null) sb.append("    value: ").append(toIndentedString(value)).append("\n");
    if (merchantCurrency != null) sb.append("    merchantCurrency: ").append(toIndentedString(merchantCurrency)).append("\n");
    if (merchantValue != null) sb.append("    merchantValue: ").append(toIndentedString(merchantValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      // return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

