/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package Model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Container for ACH/BACS batch payment metadata including file control fields, batch counts, and integrity checksums
 */
@ApiModel(description = "Container for ACH/BACS batch payment metadata including file control fields, batch counts, and integrity checksums")

public class UnifiedriskPaymentBatch {
  @SerializedName("batchNumber")
  private String batchNumber = null;

  @SerializedName("categoryPurposeDescription")
  private String categoryPurposeDescription = null;

  @SerializedName("endOfBatchIndicator")
  private Boolean endOfBatchIndicator = null;

  @SerializedName("endOfFileIndicator")
  private Boolean endOfFileIndicator = null;

  @SerializedName("entryDetailRecNum")
  private BigDecimal entryDetailRecNum = null;

  @SerializedName("fileIdModifier")
  private String fileIdModifier = null;

  @SerializedName("numberOfAddendaRecords")
  private BigDecimal numberOfAddendaRecords = null;

  @SerializedName("serviceClassCode")
  private String serviceClassCode = null;

  @SerializedName("totalBatchCountInFile")
  private BigDecimal totalBatchCountInFile = null;

  @SerializedName("totalBatchEntries")
  private BigDecimal totalBatchEntries = null;

  @SerializedName("totalEntryCountInFile")
  private BigDecimal totalEntryCountInFile = null;

  @SerializedName("totalEntryHash")
  private BigDecimal totalEntryHash = null;

  @SerializedName("totalTransitCountInFile")
  private BigDecimal totalTransitCountInFile = null;

  public UnifiedriskPaymentBatch batchNumber(String batchNumber) {
    this.batchNumber = batchNumber;
    return this;
  }

   /**
   * Unique sequential identifier for this batch within the batch file, used for tracking and reconciliation of ACH or BACS batch submissions
   * @return batchNumber
  **/
  @ApiModelProperty(value = "Unique sequential identifier for this batch within the batch file, used for tracking and reconciliation of ACH or BACS batch submissions")
  public String getBatchNumber() {
    return batchNumber;
  }

  public void setBatchNumber(String batchNumber) {
    this.batchNumber = batchNumber;
  }

  public UnifiedriskPaymentBatch categoryPurposeDescription(String categoryPurposeDescription) {
    this.categoryPurposeDescription = categoryPurposeDescription;
    return this;
  }

   /**
   * Human-readable description of the business purpose for the batch (e.g., \&quot;Payroll\&quot;, \&quot;Vendor Payments\&quot;). Corresponds to the ISO 20022 CategoryPurpose code
   * @return categoryPurposeDescription
  **/
  @ApiModelProperty(value = "Human-readable description of the business purpose for the batch (e.g., \"Payroll\", \"Vendor Payments\"). Corresponds to the ISO 20022 CategoryPurpose code")
  public String getCategoryPurposeDescription() {
    return categoryPurposeDescription;
  }

  public void setCategoryPurposeDescription(String categoryPurposeDescription) {
    this.categoryPurposeDescription = categoryPurposeDescription;
  }

  public UnifiedriskPaymentBatch endOfBatchIndicator(Boolean endOfBatchIndicator) {
    this.endOfBatchIndicator = endOfBatchIndicator;
    return this;
  }

   /**
   * Indicates this entry is the last record in the current batch. Used to signal batch boundary during file processing
   * @return endOfBatchIndicator
  **/
  @ApiModelProperty(value = "Indicates this entry is the last record in the current batch. Used to signal batch boundary during file processing")
  public Boolean EndOfBatchIndicator() {
    return endOfBatchIndicator;
  }

  public void setEndOfBatchIndicator(Boolean endOfBatchIndicator) {
    this.endOfBatchIndicator = endOfBatchIndicator;
  }

  public UnifiedriskPaymentBatch endOfFileIndicator(Boolean endOfFileIndicator) {
    this.endOfFileIndicator = endOfFileIndicator;
    return this;
  }

   /**
   * Indicates this entry is the last record in the entire batch file. Used to trigger final file validation and processing
   * @return endOfFileIndicator
  **/
  @ApiModelProperty(value = "Indicates this entry is the last record in the entire batch file. Used to trigger final file validation and processing")
  public Boolean EndOfFileIndicator() {
    return endOfFileIndicator;
  }

  public void setEndOfFileIndicator(Boolean endOfFileIndicator) {
    this.endOfFileIndicator = endOfFileIndicator;
  }

  public UnifiedriskPaymentBatch entryDetailRecNum(BigDecimal entryDetailRecNum) {
    this.entryDetailRecNum = entryDetailRecNum;
    return this;
  }

   /**
   * Sequential record number of the entry detail record within the batch, used for file integrity checks and record-level reconciliation
   * @return entryDetailRecNum
  **/
  @ApiModelProperty(value = "Sequential record number of the entry detail record within the batch, used for file integrity checks and record-level reconciliation")
  public BigDecimal getEntryDetailRecNum() {
    return entryDetailRecNum;
  }

  public void setEntryDetailRecNum(BigDecimal entryDetailRecNum) {
    this.entryDetailRecNum = entryDetailRecNum;
  }

  public UnifiedriskPaymentBatch fileIdModifier(String fileIdModifier) {
    this.fileIdModifier = fileIdModifier;
    return this;
  }

   /**
   * Single character modifier (A-Z) used to distinguish multiple batch files submitted on the same day for the same originator
   * @return fileIdModifier
  **/
  @ApiModelProperty(value = "Single character modifier (A-Z) used to distinguish multiple batch files submitted on the same day for the same originator")
  public String getFileIdModifier() {
    return fileIdModifier;
  }

  public void setFileIdModifier(String fileIdModifier) {
    this.fileIdModifier = fileIdModifier;
  }

  public UnifiedriskPaymentBatch numberOfAddendaRecords(BigDecimal numberOfAddendaRecords) {
    this.numberOfAddendaRecords = numberOfAddendaRecords;
    return this;
  }

   /**
   * Count of addenda records associated with this batch entry, used for validating batch completeness during file processing
   * @return numberOfAddendaRecords
  **/
  @ApiModelProperty(value = "Count of addenda records associated with this batch entry, used for validating batch completeness during file processing")
  public BigDecimal getNumberOfAddendaRecords() {
    return numberOfAddendaRecords;
  }

  public void setNumberOfAddendaRecords(BigDecimal numberOfAddendaRecords) {
    this.numberOfAddendaRecords = numberOfAddendaRecords;
  }

  public UnifiedriskPaymentBatch serviceClassCode(String serviceClassCode) {
    this.serviceClassCode = serviceClassCode;
    return this;
  }

   /**
   * ACH service class code indicating the type of entries in the batch. Values - \&quot;200\&quot; (mixed), \&quot;220\&quot; (credits only), \&quot;225\&quot; (debits only), \&quot;280\&quot; (automated accounting)
   * @return serviceClassCode
  **/
  @ApiModelProperty(value = "ACH service class code indicating the type of entries in the batch. Values - \"200\" (mixed), \"220\" (credits only), \"225\" (debits only), \"280\" (automated accounting)")
  public String getServiceClassCode() {
    return serviceClassCode;
  }

  public void setServiceClassCode(String serviceClassCode) {
    this.serviceClassCode = serviceClassCode;
  }

  public UnifiedriskPaymentBatch totalBatchCountInFile(BigDecimal totalBatchCountInFile) {
    this.totalBatchCountInFile = totalBatchCountInFile;
    return this;
  }

   /**
   * Total number of batches contained in this file, used for file-level control validation and balancing
   * @return totalBatchCountInFile
  **/
  @ApiModelProperty(value = "Total number of batches contained in this file, used for file-level control validation and balancing")
  public BigDecimal getTotalBatchCountInFile() {
    return totalBatchCountInFile;
  }

  public void setTotalBatchCountInFile(BigDecimal totalBatchCountInFile) {
    this.totalBatchCountInFile = totalBatchCountInFile;
  }

  public UnifiedriskPaymentBatch totalBatchEntries(BigDecimal totalBatchEntries) {
    this.totalBatchEntries = totalBatchEntries;
    return this;
  }

   /**
   * Total count of entry detail records within this batch, used for batch-level balancing and reconciliation
   * @return totalBatchEntries
  **/
  @ApiModelProperty(value = "Total count of entry detail records within this batch, used for batch-level balancing and reconciliation")
  public BigDecimal getTotalBatchEntries() {
    return totalBatchEntries;
  }

  public void setTotalBatchEntries(BigDecimal totalBatchEntries) {
    this.totalBatchEntries = totalBatchEntries;
  }

  public UnifiedriskPaymentBatch totalEntryCountInFile(BigDecimal totalEntryCountInFile) {
    this.totalEntryCountInFile = totalEntryCountInFile;
    return this;
  }

   /**
   * Total count of all entry detail records across all batches in the file, used for file-level reconciliation
   * @return totalEntryCountInFile
  **/
  @ApiModelProperty(value = "Total count of all entry detail records across all batches in the file, used for file-level reconciliation")
  public BigDecimal getTotalEntryCountInFile() {
    return totalEntryCountInFile;
  }

  public void setTotalEntryCountInFile(BigDecimal totalEntryCountInFile) {
    this.totalEntryCountInFile = totalEntryCountInFile;
  }

  public UnifiedriskPaymentBatch totalEntryHash(BigDecimal totalEntryHash) {
    this.totalEntryHash = totalEntryHash;
    return this;
  }

   /**
   * Arithmetic sum of all routing transit numbers within the batch/file, used as a checksum for routing number validation
   * @return totalEntryHash
  **/
  @ApiModelProperty(value = "Arithmetic sum of all routing transit numbers within the batch/file, used as a checksum for routing number validation")
  public BigDecimal getTotalEntryHash() {
    return totalEntryHash;
  }

  public void setTotalEntryHash(BigDecimal totalEntryHash) {
    this.totalEntryHash = totalEntryHash;
  }

  public UnifiedriskPaymentBatch totalTransitCountInFile(BigDecimal totalTransitCountInFile) {
    this.totalTransitCountInFile = totalTransitCountInFile;
    return this;
  }

   /**
   * Total count of distinct routing transit numbers in the file, used for clearing house validation and routing verification
   * @return totalTransitCountInFile
  **/
  @ApiModelProperty(value = "Total count of distinct routing transit numbers in the file, used for clearing house validation and routing verification")
  public BigDecimal getTotalTransitCountInFile() {
    return totalTransitCountInFile;
  }

  public void setTotalTransitCountInFile(BigDecimal totalTransitCountInFile) {
    this.totalTransitCountInFile = totalTransitCountInFile;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnifiedriskPaymentBatch unifiedriskPaymentBatch = (UnifiedriskPaymentBatch) o;
    return Objects.equals(this.batchNumber, unifiedriskPaymentBatch.batchNumber) &&
        Objects.equals(this.categoryPurposeDescription, unifiedriskPaymentBatch.categoryPurposeDescription) &&
        Objects.equals(this.endOfBatchIndicator, unifiedriskPaymentBatch.endOfBatchIndicator) &&
        Objects.equals(this.endOfFileIndicator, unifiedriskPaymentBatch.endOfFileIndicator) &&
        Objects.equals(this.entryDetailRecNum, unifiedriskPaymentBatch.entryDetailRecNum) &&
        Objects.equals(this.fileIdModifier, unifiedriskPaymentBatch.fileIdModifier) &&
        Objects.equals(this.numberOfAddendaRecords, unifiedriskPaymentBatch.numberOfAddendaRecords) &&
        Objects.equals(this.serviceClassCode, unifiedriskPaymentBatch.serviceClassCode) &&
        Objects.equals(this.totalBatchCountInFile, unifiedriskPaymentBatch.totalBatchCountInFile) &&
        Objects.equals(this.totalBatchEntries, unifiedriskPaymentBatch.totalBatchEntries) &&
        Objects.equals(this.totalEntryCountInFile, unifiedriskPaymentBatch.totalEntryCountInFile) &&
        Objects.equals(this.totalEntryHash, unifiedriskPaymentBatch.totalEntryHash) &&
        Objects.equals(this.totalTransitCountInFile, unifiedriskPaymentBatch.totalTransitCountInFile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(batchNumber, categoryPurposeDescription, endOfBatchIndicator, endOfFileIndicator, entryDetailRecNum, fileIdModifier, numberOfAddendaRecords, serviceClassCode, totalBatchCountInFile, totalBatchEntries, totalEntryCountInFile, totalEntryHash, totalTransitCountInFile);
  }


  private static final java.util.regex.Pattern SENSITIVE_FIELD_PATTERN =
      java.util.regex.Pattern.compile(
          "^(password|apiKey|accessToken|refreshToken|clientSecret|secret|secretKey"
          + "|passphrase|privateKey|authToken|bearerToken|idToken"
          + "|sharedSecret|webhookSecret|keyPassword|encryptionKey|signingKey"
          + "|cardNumber|pan|cvv|cvn|cvv2|securityCode|pin|accountNumber"
          + "|number|expirationMonth|expirationYear|ssn|taxId)$");

  /**
   * Returns a masked string representation of this object.
   * Sensitive fields (passwords, API keys, card numbers, etc.) are replaced
   * with {@code [REDACTED]} to prevent accidental exposure in logs.
   *
   * <p>To inspect sensitive field values during local debugging, use
   * {@link #toDebugString()} instead, or call the individual getter methods.
   *
   * @return masked string representation
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnifiedriskPaymentBatch {\n");
    
    if (batchNumber != null) sb.append("    batchNumber: ").append(SENSITIVE_FIELD_PATTERN.matcher("batchNumber").matches() ? "[REDACTED]" : toIndentedString(batchNumber)).append("\n");
    if (categoryPurposeDescription != null) sb.append("    categoryPurposeDescription: ").append(SENSITIVE_FIELD_PATTERN.matcher("categoryPurposeDescription").matches() ? "[REDACTED]" : toIndentedString(categoryPurposeDescription)).append("\n");
    if (endOfBatchIndicator != null) sb.append("    endOfBatchIndicator: ").append(SENSITIVE_FIELD_PATTERN.matcher("endOfBatchIndicator").matches() ? "[REDACTED]" : toIndentedString(endOfBatchIndicator)).append("\n");
    if (endOfFileIndicator != null) sb.append("    endOfFileIndicator: ").append(SENSITIVE_FIELD_PATTERN.matcher("endOfFileIndicator").matches() ? "[REDACTED]" : toIndentedString(endOfFileIndicator)).append("\n");
    if (entryDetailRecNum != null) sb.append("    entryDetailRecNum: ").append(SENSITIVE_FIELD_PATTERN.matcher("entryDetailRecNum").matches() ? "[REDACTED]" : toIndentedString(entryDetailRecNum)).append("\n");
    if (fileIdModifier != null) sb.append("    fileIdModifier: ").append(SENSITIVE_FIELD_PATTERN.matcher("fileIdModifier").matches() ? "[REDACTED]" : toIndentedString(fileIdModifier)).append("\n");
    if (numberOfAddendaRecords != null) sb.append("    numberOfAddendaRecords: ").append(SENSITIVE_FIELD_PATTERN.matcher("numberOfAddendaRecords").matches() ? "[REDACTED]" : toIndentedString(numberOfAddendaRecords)).append("\n");
    if (serviceClassCode != null) sb.append("    serviceClassCode: ").append(SENSITIVE_FIELD_PATTERN.matcher("serviceClassCode").matches() ? "[REDACTED]" : toIndentedString(serviceClassCode)).append("\n");
    if (totalBatchCountInFile != null) sb.append("    totalBatchCountInFile: ").append(SENSITIVE_FIELD_PATTERN.matcher("totalBatchCountInFile").matches() ? "[REDACTED]" : toIndentedString(totalBatchCountInFile)).append("\n");
    if (totalBatchEntries != null) sb.append("    totalBatchEntries: ").append(SENSITIVE_FIELD_PATTERN.matcher("totalBatchEntries").matches() ? "[REDACTED]" : toIndentedString(totalBatchEntries)).append("\n");
    if (totalEntryCountInFile != null) sb.append("    totalEntryCountInFile: ").append(SENSITIVE_FIELD_PATTERN.matcher("totalEntryCountInFile").matches() ? "[REDACTED]" : toIndentedString(totalEntryCountInFile)).append("\n");
    if (totalEntryHash != null) sb.append("    totalEntryHash: ").append(SENSITIVE_FIELD_PATTERN.matcher("totalEntryHash").matches() ? "[REDACTED]" : toIndentedString(totalEntryHash)).append("\n");
    if (totalTransitCountInFile != null) sb.append("    totalTransitCountInFile: ").append(SENSITIVE_FIELD_PATTERN.matcher("totalTransitCountInFile").matches() ? "[REDACTED]" : toIndentedString(totalTransitCountInFile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Returns an unmasked string representation of this object, including all
   * sensitive field values in plaintext.
   *
   * <p><b>WARNING:</b> For local debugging only. Never pass this output to a
   * logger or include it in error messages in production environments, as it
   * will expose credentials, card numbers, and other sensitive data.
   *
   * @return unmasked string representation
   */
  public String toDebugString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnifiedriskPaymentBatch {\n");
    
    if (batchNumber != null) sb.append("    batchNumber: ").append(toIndentedString(batchNumber)).append("\n");
    if (categoryPurposeDescription != null) sb.append("    categoryPurposeDescription: ").append(toIndentedString(categoryPurposeDescription)).append("\n");
    if (endOfBatchIndicator != null) sb.append("    endOfBatchIndicator: ").append(toIndentedString(endOfBatchIndicator)).append("\n");
    if (endOfFileIndicator != null) sb.append("    endOfFileIndicator: ").append(toIndentedString(endOfFileIndicator)).append("\n");
    if (entryDetailRecNum != null) sb.append("    entryDetailRecNum: ").append(toIndentedString(entryDetailRecNum)).append("\n");
    if (fileIdModifier != null) sb.append("    fileIdModifier: ").append(toIndentedString(fileIdModifier)).append("\n");
    if (numberOfAddendaRecords != null) sb.append("    numberOfAddendaRecords: ").append(toIndentedString(numberOfAddendaRecords)).append("\n");
    if (serviceClassCode != null) sb.append("    serviceClassCode: ").append(toIndentedString(serviceClassCode)).append("\n");
    if (totalBatchCountInFile != null) sb.append("    totalBatchCountInFile: ").append(toIndentedString(totalBatchCountInFile)).append("\n");
    if (totalBatchEntries != null) sb.append("    totalBatchEntries: ").append(toIndentedString(totalBatchEntries)).append("\n");
    if (totalEntryCountInFile != null) sb.append("    totalEntryCountInFile: ").append(toIndentedString(totalEntryCountInFile)).append("\n");
    if (totalEntryHash != null) sb.append("    totalEntryHash: ").append(toIndentedString(totalEntryHash)).append("\n");
    if (totalTransitCountInFile != null) sb.append("    totalTransitCountInFile: ").append(toIndentedString(totalTransitCountInFile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      // return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

