name: Java workflow to run Java rest Samples
on:
  push:
env:
  CLIENT_FOLDER: 'cybersource-rest-client-java'
  SAMPLE_FOLDER: 'cybersource-rest-samples-java'
jobs:
    complete-job:
        defaults:
            run:
              shell: bash
        strategy:
            matrix:
              operating-system: [ubuntu-latest,macos-latest,windows-latest]
        runs-on: ${{matrix.operating-system}}
        continue-on-error: true
        steps:
            - name: Making separate folders
              run: |
                rm -rf $CLIENT_FOLDER
                rm -rf $SAMPLE_FOLDER
                mkdir $CLIENT_FOLDER $SAMPLE_FOLDER
            - name: Adding client
              uses: actions/checkout@v4
              with:
                path: ${{env.CLIENT_FOLDER}}
                ref: 'adding-workflows'
            - name: Adding sample
              uses: actions/checkout@v4
              with:
                repository: 'CyberSource/cybersource-rest-samples-java'
                ref: 'testing-branch'
                path: ${{env.SAMPLE_FOLDER}}
            - name: Building the Projects
              run: |
                mvn -version
                cd $CLIENT_FOLDER
                mvn clean install
                cd ..
                cd $SAMPLE_FOLDER
                mvn clean install
                echo "Done Building"
            - name: Upload the log files and report pdf
              uses: actions/upload-artifact@v3
              with:
                name: log-files
                path: |
                  ${{env.SAMPLE_FOLDER}}
                  ${{env.CLIENT_FOLDER}}