name: Java workflow to run Java rest Samples
on:
  push:
env:
  CLIENT_FOLDER: 'cybersource-rest-client-java'
  SAMPLE_FOLDER: 'cybersource-rest-samples-java'
jobs:
    complete-job:
        defaults:
            run:
              shell: bash
        strategy:
            matrix:
              operating-system: [ubuntu-latest,macos-latest,windows-latest]
            #   java-version: ['3.6','3.7','3.8','3.9','3.10','3.11','3.12']
            #   include:
            #     - operating-system: ubuntu-20.04
            #       pyth-version: '3.6'
            #     - operating-system: macos-13
            #       pyth-version: '3.6'
            #     - operating-system: macos-13
            #       pyth-version: '3.7'
            #   exclude:
            #     - operating-system: macos-latest
            #       pyth-version: '3.6'
            #     - operating-system: macos-latest
            #       pyth-version: '3.7'
            #     - operating-system: ubuntu-latest
            #       pyth-version: '3.6'
            #     - operating-system: windows-latest
            #       pyth-version: '3.6'
        runs-on: ${{matrix.operating-system}}
        continue-on-error: true
        steps:
            - name: Making separate folders
              run: |
                rm -rf $CLIENT_FOLDER
                rm -rf $SAMPLE_FOLDER
                mkdir $CLIENT_FOLDER $SAMPLE_FOLDER
            - name: Adding client
              uses: actions/checkout@v4
              with:
                path: ${{env.CLIENT_FOLDER}}
            - name: Adding sample
              uses: actions/checkout@v4
              with:
                repository: 'CyberSource/cybersource-rest-samples-java'
                ref: 'testing-branch'
                path: ${{env.SAMPLE_FOLDER}}
            - name: Building the Projects
              run: |
                cd '$CLIENT_FOLDER'
                mvn clean install
                cd ..
                cd '$SAMPLE_FOLDER'
                mvn clean install
                echo "Done Building"
